name: "browser"
on:
  push:
    branches:
      - main
    paths:
      - "apps/browser/**"
      - "packages/server/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: deploy-browser
    defaults:
      run:
        working-directory: ./apps/browser
    env:
      CLERK_FRONTEND_API: ${{ secrets.CLERK_FRONTEND_API }}
      PLASMO_PUBLIC_CLERK_SYNC_HOST: ${{ secrets.PLASMO_PUBLIC_CLERK_SYNC_HOST }}

    steps:
      - name: ğŸ’¾ Checkout code
        uses: actions/checkout@v4

      - name: ğŸ“¦ Setup bun
        uses: oven-sh/setup-bun@v2

      - name: ğŸ“¦ Install dependencies
        run: bun ci

      - name: ğŸ› ï¸ Build the Chrome Extension
        run: bun run build

      - name: ğŸ› ï¸ Package the extension into a zip artifact
        run: bun run package

      - name: ğŸš€ Upload to Chrome Web Store
        uses: mobilefirstllc/cws-publish@latest
        with:
          action: "upload" # one of: upload, publish, testers
          client_id: ${{ secrets.CLIENT }}
          client_secret: ${{ secrets.SECRET }}
          refresh_token: ${{ secrets.TOKEN }}
          extension_id: "bbhdnidgcmmpihfimomooiaojnaeedlj"
          zip_file: "./apps/browser/build/chrome-mv3-prod.zip"
